name: Run Recaptcha Solver

on:
  workflow_dispatch:

jobs:
  solve_recaptcha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install ffmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          pip install -r requirements.txt
          
      - name: Run Recaptcha Solver script
        run: xvfb-run python recaptcha_solver.py

      - name: Upload screenshot
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: screenshot.png

      - name: Commit and Push Results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add screenshot.png
          git commit -m "Add Recaptcha Solver screenshot" || echo "No changes to commit"
          git push
