name: Run Recaptcha Solver

on:
  workflow_dispatch:

jobs:
  solve_recaptcha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb ffmpeg
          pip install selenium_recaptcha_solver undetected-chromedriver==3.4.6

      - name: Run Recaptcha Solver script
        run: xvfb-run python recaptcha_solver.py

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: |
            screenshot.png
            nowsecure_screenshot.png
            error_screenshot.png

      - name: Commit and Push Results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add screenshot.png nowsecure_screenshot.png error_screenshot.png
          git commit -m "Add screenshots from Recaptcha Solver and nowsecure.nl" || echo "No changes to commit"
          git push
